name: PowerEmissions

channels:
  - conda-forge
  
dependencies:
  - python>=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - seaborn
  - twine
  - mkdocs
  - mkdocs-material
  - typer
  - dask
  - tabulate
  - pip
  
  - pip:
      - -e .
      - nbdev
      - ipypb
      - feautils
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix